######################################################################
# Automatically generated by qmake (3.0) Mon Feb 24 01:02:40 2014
######################################################################

TEMPLATE = app
TARGET = osmquark
INCLUDEPATH += .
QT = core gui network widgets
CONFIG += debug c++11

# Input
HEADERS += osmwindow.h osmtiles.h
SOURCES += osmwindow.cpp osmtiles.cpp main.cpp
